### ISSUE TITLE
This value is not valid 

### ISSUE THREAD

**Issue by mudrd8mz** [abkoch/imprint#2]
This validation error does not say much:

![image](https://github.com/abkoch/imprint/assets/85831/9f25b714-5aab-43e1-9552-dc276e0916f7)

Maybe it would help to name the field as "Privacy rules link" and the error could read "Not a valid link address" or "Not a valid URL" or so.

Also, there is a typo in the word "ressource" - it should read just "resource"

**Comment by abkoch** [comment]
Thank you, @mudrd8mz. It's fixed in https://github.com/abkoch/imprint/releases/tag/v1.0.1 and looks as follows:

![Errortext](https://github.com/abkoch/imprint/assets/51958234/66b4e44a-f23a-4a89-80d0-fce92ecc39ff)
